version: '3.4'
services:
  db:
    image: postgres:alpine
    restart: on-failure
    env_file:
      - ".env"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: on-failure
    expose:
      - 6379
    volumes:
      - redis:/data

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  app:
    image: elplano_development
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=python2 build-base
        - RAILS_ENV=development
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - sidekiq
    volumes:
      - .:/app

volumes:
  postgres:
  redis:
