version: '3.4'
services:
  db:
    image: postgres:alpine
    restart: on-failure
    env_file:
      - ".env"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis:/data

  app:
    image: elplano_development
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=python2 build-base
        - RAILS_ENV=development
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres:
  redis:
