# config/elplano.yml for rails-settings-cached
defaults: &defaults
  # Built in monitoring settings
  monitoring:
    # IP whitelist to access monitoring endpoints
    ip_whitelist:
      - 127.0.0.0/8

  rack_attack:
    ip_whitelist:
      - 127.0.0.0/8

  core:
    ## Web server settings (note: host is the FQDN, do not include http://)
    host: localhost
    port: 80 # Set to 443 if using HTTPS, see installation.md#using-https for additional HTTPS configuration details
    https: false # Set to true if using HTTPS, see installation.md#using-https for additional HTTPS configuration details

    ## Email settings
    # Email address used in the "From" field in mails sent by El Plano
    email_from: example@example.com
    email_display_name: El Plano
    email_reply_to: noreply@example.com
    email_subject_suffix: ''

  gravatar:
    plain_url: 'https://www.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon'
    ssl_url: 'https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
