development:
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  #
  # url: redis://localhost:6380
  # sentinels:
  #   -
  #     host: localhost
  #     port: 26380 # point to sentinel, not to redis port
  #   -
  #     host: slave2
  #     port: 26380 # point to sentinel, not to redis port
test:
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  #
  # url: redis://localhost:6380
production:
  # Redis (single instance)
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>

  # url: redis://master:6380
  # sentinels:
  #   -
  #     host: slave1
  #     port: 26380 # point to sentinel, not to redis port
  #   -
  #     host: slave2
  #     port: 26380 # point to sentinel, not to redis port
