development:
  url: <%= ENV['REDIS_SESSIONS_URL'] || 'redis://localhost:6379/12' %>
  #
  # url: redis://localhost:6381
  # sentinels:
  #   -
  #     host: localhost
  #     port: 26381 # point to sentinel, not to redis port
  #   -
  #     host: slave2
  #     port: 26381 # point to sentinel, not to redis port
test:
  url: <%= ENV['REDIS_SESSIONS_URL'] || 'redis://localhost:6379/12' %>
  #
  # url: redis://localhost:6381
production:
  # Redis (single instance)
  url: <%= ENV['REDIS_SESSIONS_URL'] || 'redis://localhost:6379/12' %>
  ##
  # Redis + Sentinel (for HA)
  #
  # Please read instructions carefully before using it as you may lose data:
  # http://redis.io/topics/sentinel
  #
  # You must specify a list of a few sentinels that will handle client connection
  ##
  # url: redis://master:6381
  # sentinels:
  #   -
  #     host: slave1
  #     port: 26381 # point to sentinel, not to redis port
  #   -
  #     host: slave2
  #     port: 26381 # point to sentinel, not to redis port
