development:
  url: redis://localhost:6379/10
  #
  # url: redis://localhost:6380
  # sentinels:
  #   -
  #     host: localhost
  #     port: 26380 # point to sentinel, not to redis port
  #   -
  #     host: slave2
  #     port: 26380 # point to sentinel, not to redis port
test:
  url: redis://localhost:6379/10
  #
  # url: redis://localhost:6380
production:
  # Redis (single instance)
  url: unix:/var/run/redis/redis.cache.sock

  # url: redis://master:6380
  # sentinels:
  #   -
  #     host: slave1
  #     port: 26380 # point to sentinel, not to redis port
  #   -
  #     host: slave2
  #     port: 26380 # point to sentinel, not to redis port
