---
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

:queues:
  - [mailers, 2]
  - [default, 1]

:schedule:
  clear_tokens:
    cron: '0 0 0 * * 0' # At 00:00 on Sunday.
    description: 'Deletes all revoked and expired access tokens.'
    class: Users::Tokens::ClearWorker

